allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Bu satırı şimdilik kaldırıyoruz; :app bulunamadığı anlarda sorun çıkarabiliyor
// subprojects {
//     project.evaluationDependsOn(':app')
// }

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
